language: node_js
node_js:
  - '10'
install:
  - npm install -g codecov
script:
  - yarn install
  - yarn build
  - yarn flow-typed
  - yarn lint
  - yarn test:coverage --runInBand --no-cache
  - yarn test --runInBand --no-cache
cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  repo: christopherkade/christopherkade.github.io
  fqdn: christopherkade.com
  target_branch: master
  on:
    branch: code
