language: node_js
node_js:
  - "10"
install:
  - npm install -g codecov
script:
  - yarn install
  - yarn build
  - yarn lint
cache:
  directories:
    - node_modules

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  local_dir: public
  repo: christopherkade/christopherkade.github.io
  fqdn: christopherkade.com
  target_branch: master
  on:
    branch: code
