language: node_js
node_js:
  - "10"
install:
  - npm install -g codecov
script:
  - yarn install
  - yarn build
  - yarn flow-typed
  - yarn lint
cache:
  directories:
    - node_modules

deploy:
  strategy: git
  provider: pages
  cleanup: false
  github-token: $GITHUB_TOKEN
  local_dir: public
  repo: christopherkade/christopherkade.github.io
  fqdn: christopherkade.com
  target_branch: master
  on:
    branch: code
